dist: xenial
language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
    - nightly
jobs:
    fast_finish: true
    allow_failures:
        - python: nightly
install:
    - python -m pip install --requirement requirements.txt
    - python -m pip install --requirement requirements-dev.txt
    - python -m pip install --editable .
script:
    - python -m flake8
    - python -m flake8 --print-dlint-linters
    - python -m pytest --cov
after_success:
    - coveralls
