dist: xenial
language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
    - nightly
jobs:
    fast_finish: true
    allow_failures:
        - python: nightly
install:
    - pip install --requirement requirements.txt
    - pip install --requirement requirements-dev.txt
    - pip install --editable .
script:
    - flake8
    - flake8 --print-dlint-linters
    - pytest --cov
after_success:
    - coveralls
